# Notebook para los códigos del TFG

## Librerias necesarias

### Instalamos las librerias

In [3]:
#%pip install pandas
#%pip install pysr

Requirement already satisfied: pandas in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pysr in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (0.19.4)
Requirement already satisfied: sympy<2.0.0,>=1.0.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (1.13.2)
Requirement already satisfied: pandas<3.0.0,>=0.21.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (2.2.2)
Requirement already satisfied: numpy<3.0.0,>=1.13.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (1.26.4)
Requirement already satisfied: scikit-learn<2.0.0,>=1.0.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (1.5.2)
Requirement already satisfied: juliacall==0.9.23 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (0.9.23)
Requirement already satisfied: click<9.0.0,>=7.0.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (8.1.7)
Requirement already satisfied: setuptools>=50.0.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pysr) (65.5.0)
Requirement already satisfied: juliapkg~=0.1.8 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from juliacall==0.9.23->pysr) (0.1.13)
Requirement already satisfied: colorama in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from click<9.0.0,>=7.0.0->pysr) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas<3.0.0,>=0.21.0->pysr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas<3.0.0,>=0.21.0->pysr) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from pandas<3.0.0,>=0.21.0->pysr) (2024.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (3.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from sympy<2.0.0,>=1.0.0->pysr) (1.3.0)
Requirement already satisfied: semver~=3.0 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from juliapkg~=0.1.8->juliacall==0.9.23->pysr) (3.0.2)
Requirement already satisfied: six>=1.5 in c:\users\alvar\desktop\code\programación\latex\universidad\cuarto\tfg\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=0.21.0->pysr) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

### Importamos las librerias

In [1]:
import pandas as pd
from pysr import PySRRegressor

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

# Abrir los archivos

## Abrimos el archivo physical properties

In [2]:
physical_properties = 'Data/hlsp_candels_hst_wfc3_egs_multi_v1_physpar-cat.txt'

phys_prop_data = pd.read_csv(physical_properties, sep='\s+', header=None, skiprows=123)



#A continuación añadimos las columnas

phys_prop_data.columns = ["ID",                
" age_2a_tau        (dex(yr)) ",
" tau_2a_tau        (Gyr) ",
" Av_2a_tau         (mag) ",
" SFR_2a_tau        (solMass/yr) ",
" chi2_2a_tau       ",
" age_4b            (dex(yr)) ",
" EBV_4b            (mag) ",
" age_6a_tau        (dex(yr)) ",
" tau_6a_tau        (Gyr) ",
" EBV_6a_tau        (mag) ",
" SFR_6a_tau        (solMass/yr) ",
" met_6a_tau        (solMet) ",
" extlw_6a_tau      ",
" chi2_6a_tau       ",
" L1400_6a_tau      (erg/s/Hz) ",
" L2700_6a_tau      (erg/s/Hz) ",
" UMag_6a_tau       (mag) ",
" BMag_6a_tau       (mag) ",
" VMag_6a_tau       (mag) ",
" RMag_6a_tau       (mag) ",
" IMag_6a_tau       (mag) ",
" JMag_6a_tau       (mag) ",
" KMag_6a_tau       (mag) ",
" age_10c           (dex(yr)) ",
" SFH_10c           ",
" tau_10c           (Gyr) ",
" met_10c           (solMet) ",
" M_l99_11a_tau     (dex(solMass))", 
" M_u99_11a_tau     (dex(solMass))", 
" age_11a_tau       (dex(yr)) ",
" SFR_11a_tau       (solMass/yr) ",
" M_l68_12a         (dex(solMass))",
" M_u68_12a         (dex(solMass))", 
" M_l95_12a         (dex(solMass))", 
" M_u95_12a         (dex(solMass))", 
" age_12a           (dex(yr)) ",
" tau_12a           (Gyr) ",
" EBV_12a           (mag) ",
" met_12a           (solMet) ",
" Lbol_12a          (dex(solLum)) ",
" chi2_12a          ",
" age_13a_tau       (dex(yr)) ",
" tau_13a_tau       (Gyr) ",
" Av_13a_tau        (mag) ",
" SFR_13a_tau       (solMass/yr) ",
" chi2_13a_tau      ",
" age_14a           (dex(yr)) ",
" SFH_14a           ",
" tau_14a           (Gyr) ",
" EBV_14a           (mag) ",
" SFR_14a           (solMass/yr) ",
" q_14a             ",
" age_6a_tau^NEB    (dex(yr)) ",
" tau_6a_tau^NEB    (Gyr) ",
" EBV_6a_tau^NEB    (mag) ",
" SFR_6a_tau^NEB    (solMass/yr) ",
" met_6a_tau^NEB    (solMet) ",
" extlw_6a_tau^NEB  ",
" chi2_6a_tau^NEB   ",
" L1400_6a_tau^NEB  (erg/s/Hz) ",
" L2700_6a_tau^NEB  (erg/s/Hz) ",
" UMag_6a_tau^NEB   (mag) ",
" BMag_6a_tau^NEB   (mag) ",
" VMag_6a_tau^NEB   (mag) ",
" RMag_6a_tau^NEB   (mag) ",
" IMag_6a_tau^NEB   (mag) ",
" JMag_6a_tau^NEB   (mag) ",
" KMag_6a_tau^NEB   (mag) ",
" age_6a_deltau     (dex(yr)) ",
" tau_6a_deltau     (Gyr) ",
" EBV_6a_deltau     (mag) ",
" SFR_6a_deltau     (solMass/yr) ",
" met_6a_deltau     (solMet) ",
" extlw_6a_deltau   ",
" chi2_6a_deltau    ",
" L1400_6a_deltau   (erg/s/Hz) ",
" L2700_6a_deltau   (erg/s/Hz) ",
" UMag_6a_deltau    (mag) ",
" BMag_6a_deltau    (mag) ",
" VMag_6a_deltau    (mag) ",
" RMag_6a_deltau    (mag) ",
" IMag_6a_deltau    (mag) ",
" JMag_6a_deltau    (mag) ",
" KMag_6a_deltau    (mag) ",
" age_6a_invtau     (dex(yr)) ",
" tau_6a_invtau     (Gyr) ",
" EBV_6a_invtau     (mag) ",
" SFR_6a_invtau     (solMass/yr) ",
" met_6a_invtau     (solMet) ",
" extlw_6a_invtau   ",
" chi2_6a_invtau    ",
" L1400_6a_invtau   (erg/s/Hz) ",
" L2700_6a_invtau   (erg/s/Hz) ",
" UMag_6a_invtau    (mag) ",
" BMag_6a_invtau    (mag) ",
" VMag_6a_invtau    (mag) ",
" RMag_6a_invtau    (mag) ",
" IMag_6a_invtau    (mag) ",
" JMag_6a_invtau    (mag) ",
" KMag_6a_invtau    (mag) ",
" age_10c^dust      (dex(yr)) ",
" SFH_10c^dust      ",
" tau_10c^dust      (Gyr) ",
" met_10c^dust      (solMet) ",
" age_14a_const     (dex(yr)) ",
" EBV_14a_const     (mag) ",
" SFR_14a_const     (solMass/yr) ",
" q_14a_const       ",
" age_14a_lin       (dex(yr)) ",
" EBV_14a_lin       (mag) ",
" SFR_14a_lin       (solMass/yr) ",
" q_14a_lin         ",
" age_14a_deltau    (dex(yr)) ",
" tau_14a_deltau    (Gyr) ",
" EBV_14a_deltau    (mag) ",
" SFR_14a_deltau    (solMass/yr) ",
" q_14a_deltau      ",
" age_14a_tau       (dex(yr)) ",
" tau_14a_tau       (Gyr) ",
" EBV_14a_tau       (mag) ",
" SFR_14a_tau       (solMass/yr) ",
" q_14a_tau      "]

### Lo mostramos

In [3]:
phys_prop_data

,ID,age_2a_tau (dex(yr)),tau_2a_tau (Gyr),Av_2a_tau (mag),SFR_2a_tau (solMass/yr),chi2_2a_tau,age_4b (dex(yr)),EBV_4b (mag),age_6a_tau (dex(yr)),tau_6a_tau (Gyr),...,age_14a_deltau (dex(yr)),tau_14a_deltau (Gyr),EBV_14a_deltau (mag),SFR_14a_deltau (solMass/yr),q_14a_deltau,age_14a_tau (dex(yr)),tau_14a_tau (Gyr),EBV_14a_tau (mag),SFR_14a_tau (solMass/yr),q_14a_tau
0,1,7.6,12.589,3.2,102.3000,2.830,8.31,0.42,9.06,0.6,...,8.988,0.147,0.196,1.24300,2,8.888,0.146,0.217,0.67120,2
1,2,7.9,0.316,1.2,67.6100,2.280,7.00,0.36,9.00,15.0,...,8.478,0.950,0.270,48.86000,1,8.471,1.133,0.239,32.68000,1
2,3,8.5,0.501,1.1,0.7943,2.970,7.91,0.45,7.00,1.0,...,8.678,0.711,0.278,1.00000,1,8.638,0.806,0.240,0.62490,1
3,4,8.8,0.316,1.0,0.0263,1.730,9.95,0.00,7.00,15.0,...,8.950,0.237,0.201,0.02237,1,8.893,0.273,0.186,0.01253,1
4,5,8.9,0.316,0.6,0.0257,1.050,8.96,0.00,9.05,3.0,...,8.855,0.318,0.169,0.06016,1,8.770,0.418,0.156,0.04203,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41452,41453,8.6,0.316,0.0,0.4898,0.744,7.76,0.00,8.60,2.0,...,8.372,0.653,0.102,1.46500,1,8.328,0.809,0.078,1.03200,1
41453,41454,8.0,0.316,0.2,9.5500,0.858,7.00,0.15,7.00,15.0,...,8.287,0.821,0.042,9.04500,1,8.243,0.984,0.036,7.57400,1
41454,41455,8.4,0.794,2.1,0.5248,0.228,7.00,0.60,7.00,1.0,...,8.360,0.711,0.518,0.55060,1,8.347,0.488,0.463,0.34080,1
41455,41456,8.9,12.589,0.0,0.3236,1.430,9.60,0.00,9.00,5.0,...,8.369,0.726,0.066,0.61260,1,8.310,0.849,0.052,0.47420,1
41456,41457,9.1,0.794,0.0,0.2042,0.177,8.86,0.00,8.75,0.3,...,8.354,0.851,0.133,0.67480,1,8.348,0.751,0.114,0.51850,1

## Abrimos el archivo mass

In [4]:
mass = 'Data/hlsp_candels_hst_wfc3_egs_multi_v1_mass-cat.txt'

mass_data = pd.read_csv(mass, sep='\s+', header=None, skiprows=39)


#A continuación añadimos las columnas

mass_data.columns = ["ID"
,"RAdeg          (deg) "
,"DECdeg         (deg) "
,"Hmag           (mag) "
,"PhotFlag       "
,"Class_star     "
,"AGNflag        "
,"zphot          "
,"zspec          "
,"q_zspec        "
,"r_zspec        "
,"zbest          "
,"zphot_l68      "
,"zphot_u68      "
,"zphot_l95      "
,"zphot_u95      "
,"zAGN           "
,"M_neb_med      (dex(solMass)) "
,"s_neb_med      (dex(solMass)) "
,"M_med          (dex(solMass)) "
,"s_med          (dex(solMass)) "
,"M_14a_cons     (dex(solMass)) "
,"M_11a_tau      (dex(solMass)) "
,"M_6a_tau^NEB   (dex(solMass)) "
,"M_13a_tau      (dex(solMass)) "
,"M_12a_tau      (dex(solMass)) "
,"M_6a_tau       (dex(solMass)) "
,"M_2a_tau       (dex(solMass)) "
,"M_15a          (dex(solMass)) "
,"M_10c          (dex(solMass)) "
,"M_14a_lin      (dex(solMass)) "
,"M_14a_deltau   (dex(solMass)) "
,"M_14a_tau      (dex(solMass)) "
,"M_14a_inctau   (dex(solMass)) "
,"M_14a          (dex(solMass)) "
,"M_neb_med_lin  (solMass) "
,"s_neb_med_lin  (solMass) "
,"M_med_lin      (solMass) "
,"s_med_lin      (solMass)" ]

### Lo mostramos

In [5]:
mass_data

,ID,RAdeg (deg),DECdeg (deg),Hmag (mag),PhotFlag,Class_star,AGNflag,zphot,zspec,q_zspec,...,M_10c (dex(solMass)),M_14a_lin (dex(solMass)),M_14a_deltau (dex(solMass)),M_14a_tau (dex(solMass)),M_14a_inctau (dex(solMass)),M_14a (dex(solMass)),M_neb_med_lin (solMass),s_neb_med_lin (solMass),M_med_lin (solMass),s_med_lin (solMass)
0,1,215.301100,53.051206,23.309,2,0.35,0,1.700,-99.0,-99,...,10.18,10.30,10.10,10.09,10.28,10.10,10.10,0.2120,10.00,0.108
1,2,215.267143,53.027553,25.490,2,0.02,0,3.961,-99.0,-99,...,10.05,9.78,9.79,9.90,9.85,9.78,9.65,0.2120,10.00,0.289
2,3,215.303227,53.052918,25.472,2,0.06,0,1.069,-99.0,-99,...,8.35,8.28,8.33,8.40,8.31,8.38,8.65,0.1380,8.09,0.284
3,4,215.303814,53.053403,25.595,2,0.05,0,0.399,-99.0,-99,...,7.55,7.32,7.54,7.56,7.35,7.56,7.22,0.1840,7.64,0.203
4,5,215.278721,53.035869,25.699,2,0.35,0,0.455,-99.0,-99,...,6.99,7.41,7.55,7.56,7.43,7.55,7.47,0.0558,7.61,0.231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41452,41453,214.586367,52.724885,26.038,0,0.10,0,1.939,-99.0,-99,...,6.52,8.12,8.17,8.27,8.21,8.24,8.26,0.0856,8.44,0.189
41453,41454,214.601724,52.746576,25.671,2,0.12,0,4.864,-99.0,-99,...,8.96,8.83,8.87,9.04,8.96,9.02,8.60,0.3500,8.77,0.482
41454,41455,214.719360,52.819636,27.273,0,0.93,0,1.107,-99.0,-99,...,8.33,7.67,7.73,7.84,7.75,7.78,7.78,0.0635,7.89,0.880
41455,41456,214.887474,52.928586,26.303,0,0.03,0,1.586,-99.0,-99,...,7.72,7.74,7.78,7.91,7.83,7.88,8.01,0.1160,8.21,0.175
41456,41457,214.668006,52.769351,27.115,0,0.93,0,2.335,-99.0,-99,...,8.08,7.74,7.80,7.99,7.84,7.92,8.08,0.2720,8.42,0.190

## Abrimos el archivo photo

In [6]:
phot = 'Data/hlsp_candels_hst_wfc3_egs_multi_v2_redshift-cat.txt'

phot_data = pd.read_csv(phot, sep='\s+', header=None, skiprows=61)


#A continuación añadimos las columnas

phot_data.columns = [" file "
," ID (CANDELS.EGS.F160W.v1b_1.photom.cat) "
," RA (CANDELS.EGS.F160W.v1b_1.photom.cat) "
," DEC (CANDELS.EGS.F160W.v1b_1.photom.cat) "
," z_best "
," z_best_type "
," z_spec "
," z_spec_ref "
," z_grism "
,"  mFDa4_z_peak "
,"  mFDa4_z_weight "
,"  mFDa4_z683_low "
,"  mFDa4_z683_high "
,"  mFDa4_z954_low "
,"  mFDa4_z954_high "
,"  HB4_z_peak "
,"  HB4_z_weight "
,"  HB4_z683_low "
,"  HB4_z683_high "
,"  HB4_z954_low "
,"  HB4_z954_high "
,"  Finkelstein_z_peak "
,"  Finkelstein_z_weight "
,"  Finkelstein_z683_low "
,"  Finkelstein_z683_high "
,"  Finkelstein_z954_low "
,"  Finkelstein_z954_high "
,"  Fontana_z_peak "
,"  Fontana_z_weight "
,"  Fontana_z683_low "
,"  Fontana_z683_high "
,"  Fontana_z954_low "
,"  Fontana_z954_high "
,"  Pforr_z_peak "
,"  Pforr_z_weight "
,"  Pforr_z683_low "
,"  Pforr_z683_high "
,"  Pforr_z954_low "
,"  Pforr_z954_high "
,"  Salvato_z_peak "
,"  Salvato_z_weight "
,"  Salvato_z683_low "
,"  Salvato_z683_high "
,"  Salvato_z954_low "
,"  Salvato_z954_high "
,"  Wiklind_z_peak "
,"  Wiklind_z_weight "
,"  Wiklind_z683_low "
,"  Wiklind_z683_high "
,"  Wiklind_z954_low "
,"  Wiklind_z954_high "
,"  Wuyts_z_peak "
,"  Wuyts_z_weight "
,"  Wuyts_z683_low "
,"  Wuyts_z683_high "
,"  Wuyts_z954_low "
,"  Wuyts_z954_high" ]

### Lo mostramos

In [7]:
phot_data

,file,ID (CANDELS.EGS.F160W.v1b_1.photom.cat),RA (CANDELS.EGS.F160W.v1b_1.photom.cat),DEC (CANDELS.EGS.F160W.v1b_1.photom.cat),z_best,z_best_type,z_spec,z_spec_ref,z_grism,mFDa4_z_peak,...,Wiklind_z683_low,Wiklind_z683_high,Wiklind_z954_low,Wiklind_z954_high,Wuyts_z_peak,Wuyts_z_weight,Wuyts_z683_low,Wuyts_z683_high,Wuyts_z954_low,Wuyts_z954_high
0,ALL_OPTIMIZED_PDFS_EGS_ID00001.pzd,1,215.301103,53.051246,1.947,p,-1.0,--,-1.0,1.95,...,1.683,2.204,1.536,2.575,1.94,1.934,1.879,1.968,1.492,2.002
1,ALL_OPTIMIZED_PDFS_EGS_ID00002.pzd,2,215.267148,53.027599,3.980,p,-1.0,--,-1.0,3.98,...,3.566,4.084,3.310,4.318,4.00,3.978,3.864,4.098,3.705,4.212
2,ALL_OPTIMIZED_PDFS_EGS_ID00003.pzd,3,215.303229,53.052958,1.342,p,-1.0,--,-1.0,1.40,...,0.166,1.659,0.021,2.119,1.23,1.218,0.910,1.467,0.347,1.865
3,ALL_OPTIMIZED_PDFS_EGS_ID00004.pzd,4,215.303816,53.053443,0.260,p,-1.0,--,-1.0,0.00,...,0.136,0.707,0.020,3.412,0.00,0.007,0.014,0.533,0.002,0.693
4,ALL_OPTIMIZED_PDFS_EGS_ID00005.pzd,5,215.278725,53.035913,0.446,p,-1.0,--,-1.0,0.56,...,0.355,3.382,0.084,3.937,0.56,0.446,0.286,0.669,0.140,3.510
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41452,ALL_OPTIMIZED_PDFS_EGS_ID41453.pzd,41453,214.586356,52.724939,1.912,p,-1.0,--,-1.0,2.00,...,0.364,2.590,0.075,2.862,2.00,1.912,1.528,2.236,1.323,2.462
41453,ALL_OPTIMIZED_PDFS_EGS_ID41454.pzd,41454,214.601713,52.746626,4.867,p,-1.0,--,-1.0,4.84,...,4.671,4.914,4.525,5.073,4.77,4.785,4.697,4.876,4.627,4.980
41454,ALL_OPTIMIZED_PDFS_EGS_ID41455.pzd,41455,214.719359,52.819680,2.078,p,-1.0,--,-1.0,1.74,...,0.847,5.271,0.129,8.512,1.73,1.854,0.933,2.875,0.335,4.201
41455,ALL_OPTIMIZED_PDFS_EGS_ID41456.pzd,41456,214.887465,52.928631,1.590,p,-1.0,--,-1.0,1.45,...,0.375,1.990,0.045,2.468,1.45,1.590,1.266,1.915,1.016,2.171
41456,ALL_OPTIMIZED_PDFS_EGS_ID41457.pzd,41457,214.668002,52.769395,1.911,p,-1.0,--,-1.0,2.55,...,0.499,2.790,0.085,3.409,2.07,2.002,1.433,2.554,0.592,2.969

In [12]:
cosmic_noon_phot = phot_data[(1.5<phot_data[" z_best "])& (phot_data[" z_best "]<2.5)]
cosmic_noon_phot

,file,ID (CANDELS.EGS.F160W.v1b_1.photom.cat),RA (CANDELS.EGS.F160W.v1b_1.photom.cat),DEC (CANDELS.EGS.F160W.v1b_1.photom.cat),z_best,z_best_type,z_spec,z_spec_ref,z_grism,mFDa4_z_peak,...,Wiklind_z683_low,Wiklind_z683_high,Wiklind_z954_low,Wiklind_z954_high,Wuyts_z_peak,Wuyts_z_weight,Wuyts_z683_low,Wuyts_z683_high,Wuyts_z954_low,Wuyts_z954_high
0,ALL_OPTIMIZED_PDFS_EGS_ID00001.pzd,1,215.301103,53.051246,1.947,p,-1.0,--,-1.0,1.95,...,1.683,2.204,1.536,2.575,1.94,1.934,1.879,1.968,1.492,2.002
6,ALL_OPTIMIZED_PDFS_EGS_ID00007.pzd,7,215.301035,53.051430,1.567,p,-1.0,--,-1.0,1.55,...,1.645,6.789,1.453,9.641,1.50,1.522,1.432,1.618,1.351,1.774
13,ALL_OPTIMIZED_PDFS_EGS_ID00014.pzd,14,215.299993,53.051383,1.589,p,-1.0,--,-1.0,1.53,...,0.443,2.734,0.036,5.188,1.53,1.589,0.951,2.206,0.546,2.702
15,ALL_OPTIMIZED_PDFS_EGS_ID00016.pzd,16,215.299495,53.051344,1.879,p,-1.0,--,-1.0,1.60,...,1.235,2.476,0.682,2.945,1.19,1.435,1.006,1.890,0.837,2.139
17,ALL_OPTIMIZED_PDFS_EGS_ID00018.pzd,18,215.293744,53.047429,1.788,p,-1.0,--,-1.0,1.99,...,1.805,2.188,1.633,2.375,2.58,2.624,2.574,2.687,2.554,2.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41449,ALL_OPTIMIZED_PDFS_EGS_ID41450.pzd,41450,214.580315,52.721460,1.702,p,-1.0,--,-1.0,1.50,...,0.226,2.190,0.032,2.671,1.50,1.702,1.414,2.022,1.176,2.361
41452,ALL_OPTIMIZED_PDFS_EGS_ID41453.pzd,41453,214.586356,52.724939,1.912,p,-1.0,--,-1.0,2.00,...,0.364,2.590,0.075,2.862,2.00,1.912,1.528,2.236,1.323,2.462
41454,ALL_OPTIMIZED_PDFS_EGS_ID41455.pzd,41455,214.719359,52.819680,2.078,p,-1.0,--,-1.0,1.74,...,0.847,5.271,0.129,8.512,1.73,1.854,0.933,2.875,0.335,4.201
41455,ALL_OPTIMIZED_PDFS_EGS_ID41456.pzd,41456,214.887465,52.928631,1.590,p,-1.0,--,-1.0,1.45,...,0.375,1.990,0.045,2.468,1.45,1.590,1.266,1.915,1.016,2.171
41456,ALL_OPTIMIZED_PDFS_EGS_ID41457.pzd,41457,214.668002,52.769395,1.911,p,-1.0,--,-1.0,2.55,...,0.499,2.790,0.085,3.409,2.07,2.002,1.433,2.554,0.592,2.969

In [23]:
import json
def filter_redsift(phot_data,mass_data,phys_prop_data,z =[(0.0,0.4),(0.8,1.2),(1.5,2.5)]):
    db = {}
    
    for z_min, z_max in z:
        a = phot_data[(z_min<=phot_data[" z_best "])& (phot_data[" z_best "]<=z_max)]
        b = mass_data[(z_min<=phot_data[" z_best "])& (phot_data[" z_best "]<=z_max)]
        c = phys_prop_data[(z_min<=phot_data[" z_best "])& (phot_data[" z_best "]<=z_max)]
    
        db['Mass z='+str(z_min)+'-'+str(z_max)]= f"Columns:{a.shape[1]} Rows:{a.shape[0]}" 
        db['Photo z='+str(z_min)+'-'+str(z_max)]= f"Columns:{b.shape[1]} Rows:{b.shape[0]}"
        db['Phys_prop z='+str(z_min)+'-'+str(z_max)]= f"Columns:{c.shape[1]} Rows:{c.shape[0]}"
        
        
        
        
        
    
    
    return db

db = filter_redsift(phot_data,mass_data,phys_prop_data)
print(json.dumps(db,indent=2))

{
  "Mass z=0.0-0.4": "Columns:57 Rows:4517",
  "Photo z=0.0-0.4": "Columns:39 Rows:4517",
  "Phys_prop z=0.0-0.4": "Columns:123 Rows:4517",
  "Mass z=0.8-1.2": "Columns:57 Rows:4683",
  "Photo z=0.8-1.2": "Columns:39 Rows:4683",
  "Phys_prop z=0.8-1.2": "Columns:123 Rows:4683",
  "Mass z=1.5-2.5": "Columns:57 Rows:15162",
  "Photo z=1.5-2.5": "Columns:39 Rows:15162",
  "Phys_prop z=1.5-2.5": "Columns:123 Rows:15162"
}